# -*- coding: utf-8 -*-
"""evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O6dJQ4bmli_cv99ScAIyza90vOII8x1G
"""

import os

# ---------------- TOKENIZER ---------------- #

def tokenize(expr):
    tokens = []
    i = 0
    n = len(expr)

    while i < n:
        c = expr[i]

        if c.isspace():
            i += 1
            continue

        if c.isdigit():
            num = c
            i += 1
            while i < n and expr[i].isdigit():
                num += expr[i]
                i += 1
            tokens.append(("NUM", float(num)))
            continue

        if c in "+-*/":
            tokens.append(("OP", c))
            i += 1
            continue

        if c == "(":
            tokens.append(("LPAREN", c))
            i += 1
            continue

        if c == ")":
            tokens.append(("RPAREN", c))
            i += 1
            continue

        raise ValueError("Invalid token")

    tokens.append(("END", None))
    return tokens


def tokens_to_string(tokens):
    result = []
    for t, v in tokens:
        if t == "NUM":
            result.append(f"[NUM:{int(v) if v.is_integer() else v}]")
        elif t == "OP":
            result.append(f"[OP:{v}]")
        elif t == "LPAREN":
            result.append("[LPAREN:(]")
        elif t == "RPAREN":
            result.append("[RPAREN:)]")
        elif t == "END":
            result.append("[END]")
    return " ".join(result)


# ---------------- PARSER ---------------- #

def parse(tokens):
    pos = 0

    def peek():
        return tokens[pos]

    def consume(expected=None):
        nonlocal pos
        tok = tokens[pos]
        if expected and tok[0] != expected:
            raise ValueError("Unexpected token")
        pos += 1
        return tok

    def parse_expr():
        node = parse_term()
        while peek()[0] == "OP" and peek()[1] in "+-":
            op = consume()[1]
            right = parse_term()
            node = (op, node, right)
        return node

    def parse_term():
        node = parse_factor()

        while True:
            tok = peek()

            if tok[0] == "OP" and tok[1] in "*/":
                op = consume()[1]
                right = parse_factor()
                node = (op, node, right)

            elif tok[0] in ("NUM", "LPAREN"):
                right = parse_factor()
                node = ("*", node, right)

            else:
                break

        return node

    def parse_factor():
        tok = peek()

        if tok[0] == "OP" and tok[1] == "-":
            consume()
            return ("neg", parse_factor())

        if tok[0] == "OP" and tok[1] == "+":
            raise ValueError("Unary + not allowed")

        return parse_primary()

    def parse_primary():
        tok = peek()

        if tok[0] == "NUM":
            return consume()

        if tok[0] == "LPAREN":
            consume()
            node = parse_expr()
            if peek()[0] != "RPAREN":
                raise ValueError("Missing )")
            consume()
            return node

        raise ValueError("Invalid expression")

    tree = parse_expr()

    if peek()[0] != "END":
        raise ValueError("Extra input")

    return tree


# ---------------- TREE STRING ---------------- #

def tree_to_string(node):
    if isinstance(node, tuple) and node[0] == "NUM":
        val = node[1]
        return str(int(val) if val.is_integer() else val)

    if isinstance(node, tuple) and node[0] == "neg":
        return f"(neg {tree_to_string(node[1])})"

    if isinstance(node, tuple):
        op, left, right = node
        return f"({op} {tree_to_string(left)} {tree_to_string(right)})"


# ---------------- EVALUATION ---------------- #

def evaluate(node):
    if node[0] == "NUM":
        return node[1]

    if node[0] == "neg":
        return -evaluate(node[1])

    op, left, right = node
    l = evaluate(left)
    r = evaluate(right)

    if op == "+":
        return l + r
    if op == "-":
        return l - r
    if op == "*":
        return l * r
    if op == "/":
        if r == 0:
            raise ZeroDivisionError
        return l / r


# ---------------- MAIN FUNCTION ---------------- #

def evaluate_file():
    input_path = "input.txt"
    output_path = "output.txt"

    results = []

    with open(input_path, "r") as f:
        lines = [line.strip() for line in f if line.strip()]

    for expr in lines:
        try:
            tokens = tokenize(expr)
            token_str = tokens_to_string(tokens)

            tree = parse(tokens)
            tree_str = tree_to_string(tree)

        except Exception:
            results.append({
                "input": expr,
                "tree": "ERROR",
                "tokens": "ERROR",
                "result": "ERROR"
            })
            continue

        # evaluation handled separately
        try:
            result = evaluate(tree)
        except Exception:
            result = "ERROR"

        results.append({
            "input": expr,
            "tree": tree_str,
            "tokens": token_str,
            "result": result
        })

    # write output
    with open(output_path, "w") as f:
        for r in results:
            f.write(f"Input: {r['input']}\n")
            f.write(f"Tree: {r['tree']}\n")
            f.write(f"Tokens: {r['tokens']}\n")
            f.write(f"Result: {r['result']}\n\n")

    return results


# ---------------- RUN DIRECTLY ---------------- #

if __name__ == "__main__":
    evaluate_file()