# -*- coding: utf-8 -*-
"""HIT137_Question1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwJkdm8FRygzPLnTuerOx2qEiykdw5dc
"""

def shift_char(c, shift):
    """Shift character within alphabet, wrapping around."""
    if c.islower():
        base = ord('a')
        return chr((ord(c) - base + shift) % 26 + base)
    elif c.isupper():
        base = ord('A')
        return chr((ord(c) - base + shift) % 26 + base)
    return c


def encrypt_text(text, shift1, shift2):
    result = ""

    for c in text:
        if c.islower():
            if 'a' <= c <= 'm':
                shift = shift1 * shift2
                result += "1" + shift_char(c, shift)
            else:
                shift = -(shift1 + shift2)
                result += "2" + shift_char(c, shift)

        elif c.isupper():
            if 'A' <= c <= 'M':
                shift = -shift1
                result += "3" + shift_char(c, shift)
            else:
                shift = shift2 ** 2
                result += "4" + shift_char(c, shift)

        else:
            result += "0" + c  # unchanged

    return result


def decrypt_text(text, shift1, shift2):
    result = ""
    i = 0

    while i < len(text):
        code = text[i]
        c = text[i + 1]

        if code == "1":
            result += shift_char(c, -(shift1 * shift2))
        elif code == "2":
            result += shift_char(c, (shift1 + shift2))
        elif code == "3":
            result += shift_char(c, shift1)
        elif code == "4":
            result += shift_char(c, -(shift2 ** 2))
        else:
            result += c

        i += 2

    return result


def encrypt_file(shift1, shift2):
    with open("raw_text.txt", "r") as f:
        text = f.read()

    encrypted = encrypt_text(text, shift1, shift2)

    with open("encrypted_text.txt", "w") as f:
        f.write(encrypted)


def decrypt_file(shift1, shift2):
    with open("encrypted_text.txt", "r") as f:
        text = f.read()

    decrypted = decrypt_text(text, shift1, shift2)

    with open("decrypted_text.txt", "w") as f:
        f.write(decrypted)


def verify():
    with open("raw_text.txt", "r") as f:
        original = f.read()

    with open("decrypted_text.txt", "r") as f:
        decrypted = f.read()

    if original == decrypted:
        print("✅ Decryption successful: Files match!")
    else:
        print("❌ Decryption failed: Files do NOT match.")


# ===== MAIN PROGRAM =====
def main():
    shift1 = int(input("Enter shift1: "))
    shift2 = int(input("Enter shift2: "))

    encrypt_file(shift1, shift2)
    print("Encryption complete -> encrypted_text.txt")

    decrypt_file(shift1, shift2)
    print("Decryption complete -> decrypted_text.txt")

    verify()


if __name__ == "__main__":
    main()